### ISSUE TITLE
Won't open with Elite 2.3 update

### ISSUE THREAD

**Issue by Ch4rli3G0rd0n** [jtickle/Picard#33]
i can't manage to open Picard after yesterday's Elite 2.3 update. In my understanding, this program only reads the logs and doesn't communicate with the API, but i have the same issue with EDDI (unrelated project) since yesterday, so maybe something changed in Frontier's API or similar and this program is also affected in some way? Or maybe they changed the log files? I hope the issue can be sorted soon, and thanks to the dev for his precious work!

**Comment by davidgilson** [comment]
Same issue here. Windows 10 and Elite Dangerous 2.3.

**Comment by nordicpc** [comment]
Odd, mine's working just fine.

**Comment by cgoodric** [comment]
Same issue. I did update to the latest Windows 10 version (Creators update, build 1703) within the last few days also.

**Comment by Meneltarma** [comment]
Anyone else still having issues with this?

**Comment by davidgilson** [comment]
Yes!

**Comment by cgoodric** [comment]
Yes.

**Comment by jerryp-uk** [comment]
This is also not  working for me. Application fails on launch. Get .NET Runtime error. 

Event ID: 1026
`Application: Picard.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.GetErrorContext(System.Object, System.Object, System.String, System.Exception)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled(System.Object, Newtonsoft.Json.Serialization.JsonContract, System.Object, Newtonsoft.Json.IJsonLineInfo, System.String, System.Exception)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   at Newtonsoft.Json.JsonSerializer.Deserialize[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Newtonsoft.Json.JsonReader)
   at LibEDJournal.EliteJournalParser+<GetLogEntries>d__9.MoveNext()
   at Picard.CmdrChooser.ChooseCmdrController.GetCmdrs(System.String)
   at Picard.CmdrChooser.ChooseCmdrController.Run()
   at Picard.Program.Main()
`

This error is then followed by an application error event ID 1000:
`Faulting application name: Picard.exe, version: 1.0.2.0, time stamp: 0x58ab944d
Faulting module name: KERNELBASE.dll, version: 10.0.15063.296, time stamp: 0x28e9cf15
Exception code: 0xe0434352
Fault offset: 0x000eb802
Faulting process ID: 0x3614
Faulting application start time: 0x01d2fe8948604501
Faulting application path: C:\Program Files (x86)\Picard\Picard.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: e78f1dc9-daa3-47d6-b748-30bb147692d9
Faulting package full name: 
Faulting package-relative application ID: `

This is reproducible every time. I have not been able to launch Picard successfully since 2.3

**Comment by graph-di5** [comment]
I had a little debug and found, that app crashes for me on next log item
`{ "timestamp":"2017-07-10T12:36:06Z", "event":"EngineerCraft", "Engineer":"Felicity Farseer", "Blueprint":"FSD_LongRange", "Level":1, "Ingredients":[ { "Name":"disruptedwakeechoes", "Count":1 } ] }`
 with follownig json deserializer error

> {"Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.IDictionary`2[System.String,System.Int32]' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath 'Ingredients', line 1, position 149."}



But external online json validators say that this json is ok, i hope this helps.
